var action = require("./Action");
var actionLog = require("./ActionLog");
var department = require("./Department");
var departmentHead = require("./DepartmentHead");
var employee = require("./Employee");
var file = require("./File");
var fileType = require("./FileType");
var flowGroup = require("./FlowGroup");
var flowGroupMember = require("./FlowGroupMember");
var flowStep = require("./FlowStep");
var flowStepType = require("./FlowStepType");
var masterFlow = require("./MasterFlow");
var masterFlowStep = require("./MasterFlowStep");
var orgStructure = require("./OrgStructure");
var position = require("./Position");
var positionLevel = require("./PositionLevel");
var request = require("./Request");
var requestActionLog = require("./RequestActionLog");
var requestType = require("./RequestType");
var role = require("./Role");
var status = require("./Status");
var stateTransition = require("./StateTransition");
var stateType = require("./StateType");
var user = require("./User");
var borrow = require("./Borrow");
var borrowItem = require("./BorrowItem");
var equiepment = require("./Equiepment");
var equiepmentType = require("./EquiepmentType");
var gspc = require("./Gspc");
var holiday = require("./Holiday");
var itdx = require("./Itdx");
var policy = require("./Policy");
var policyDeteil = require("./PolicyDeteil");
var policyType = require("./PolicyType");



actionLog.belongsTo(action, { as: "action", foreignKey: "actionId"});
action.hasMany(actionLog, { as: "actionLog", foreignKey: "actionId"});
stateTransition.belongsTo(action, { as: "action", foreignKey: "actionId" });
action.hasMany(stateTransition, { as: "stateTransition", foreignKey: "actionId" });
requestActionLog.belongsTo(actionLog, { as: "actionLog", foreignKey: "actionLogId"});
actionLog.hasMany(requestActionLog, { as: "requestActionLog", foreignKey: "actionLogId"});
borrow.belongsTo(borrowItem, { as: "borrowItem", foreignKey: "borrowItemId"});
borrowItem.hasMany(borrow, { as: "borrow", foreignKey: "borrowItemId"});
department.belongsTo(department, { as: "parent", foreignKey: "parentId"});
department.hasMany(department, { as: "department", foreignKey: "parentId"});
departmentHead.belongsTo(department, { as: "department", foreignKey: "departmentId"});
department.hasMany(departmentHead, { as: "departmentHead", foreignKey: "departmentId"});
employee.belongsTo(department, { as: "department", foreignKey: "departmentId"});
department.hasMany(employee, { as: "employees", foreignKey: "departmentId"});
equiepment.belongsTo(department, { as: "sectionCodeDepartment", foreignKey: "sectionCode"});
department.hasMany(equiepment, { as: "equiepment", foreignKey: "sectionCode"});
departmentHead.belongsTo(employee, { as: "employee", foreignKey: "employeeId"});
employee.hasMany(departmentHead, { as: "departmentHead", foreignKey: "employeeId"});
employee.belongsTo(employee, { as: "reportTo", foreignKey: "reportToId"});
employee.hasMany(employee, { as: "employee", foreignKey: "reportToId"});
user.belongsTo(employee, { as: "employee", foreignKey: "employeeId"});
employee.hasMany(user, { as: "user", foreignKey: "employeeId"});
borrowItem.belongsTo(equiepment, { as: "equiepment", foreignKey: "equiepmentId"});
equiepment.hasMany(borrowItem, { as: "borrowItem", foreignKey: "equiepmentId"});
gspc.belongsTo(equiepment, { as: "equiepment", foreignKey: "equiepmentId"});
equiepment.hasMany(gspc, { as: "gspc", foreignKey: "equiepmentId"});
equiepment.belongsTo(equiepmentType, { as: "equiepmentType", foreignKey: "equiepmentTypeId"});
equiepmentType.hasMany(equiepment, { as: "equiepment", foreignKey: "equiepmentTypeId"});
equiepment.belongsTo(file, { as: "file", foreignKey: "fileId"});
file.hasMany(equiepment, { as: "equiepment", foreignKey: "fileId"});
itdx.belongsTo(file, { as: "scheduleFile", foreignKey: "schedule"});
file.hasMany(itdx, { as: "itdxe", foreignKey: "schedule"});
file.belongsTo(fileType, { as: "fileType", foreignKey: "fileTypeId"});
fileType.hasMany(file, { as: "file", foreignKey: "fileTypeId"});
flowGroupMember.belongsTo(flowGroup, { as: "flowGroup", foreignKey: "flowGroupId"});
flowGroup.hasMany(flowGroupMember, { as: "flowGroupMember", foreignKey: "flowGroupId"});
flowStep.belongsTo(flowGroup, { as: "flowGroup", foreignKey: "flowGroupId"});
flowGroup.hasMany(flowStep, { as: "flowStep", foreignKey: "flowGroupId"});
masterFlowStep.belongsTo(flowGroup, { as: "flowGroup", foreignKey: "flowGroupId"});
flowGroup.hasMany(masterFlowStep, { as: "masterFlowStep", foreignKey: "flowGroupId"});
request.belongsTo(flowStep, { as: "flowStepFlowStep", foreignKey: "flowStepId"});
flowStep.hasMany(request, { as: "flowStepRequest", foreignKey: "flowStepId"});
requestActionLog.belongsTo(flowStep, { as: "flowStep", foreignKey: "flowStepId"});
flowStep.hasMany(requestActionLog, { as: "requestActionLog", foreignKey: "flowStepId"});
flowStep.belongsTo(flowStepType, { as: "flowStepType", foreignKey: "flowStepTypeId"});
flowStepType.hasMany(flowStep, { as: "flowStep", foreignKey: "flowStepTypeId"});
masterFlowStep.belongsTo(flowStepType, { as: "flowStepType", foreignKey: "flowStepTypeId"});
flowStepType.hasMany(masterFlowStep, { as: "masterFlowStep", foreignKey: "flowStepTypeId"});
request.belongsTo(itdx, { as: "datum", foreignKey: "dataId"});
itdx.hasMany(request, { as: "request", foreignKey: "dataId"});
request.belongsTo(gspc, { as: "gspc", foreignKey: "dataId"});
gspc.hasMany(request, { as: "request", foreignKey: "dataId"});
request.belongsTo(borrow, { as: "borrow", foreignKey: "dataId"});
borrow.hasMany(request, { as: "request", foreignKey: "dataId"});
masterFlowStep.belongsTo(masterFlow, { as: "masterFlow", foreignKey: "masterFlowId"});
masterFlow.hasMany(masterFlowStep, { as: "masterFlowStep", foreignKey: "masterFlowId"});
request.belongsTo(masterFlow, { as: "masterFlow", foreignKey: "masterFlowId"});
masterFlow.hasMany(request, { as: "request", foreignKey: "masterFlowId"});
request.belongsTo(masterFlowStep, { as: "masterFlowStep", foreignKey: "masterFlowStepId"});
masterFlowStep.hasMany(request, { as: "request", foreignKey: "masterFlowStepId"});
requestActionLog.belongsTo(masterFlowStep, { as: "masterFlowStep", foreignKey: "masterFlowStepId"});
masterFlowStep.hasMany(requestActionLog, { as: "requestActionLog", foreignKey: "masterFlowStepId"});
department.belongsTo(orgStructure, { as: "orgStructure", foreignKey: "orgStructureId"});
orgStructure.hasMany(department, { as: "department", foreignKey: "orgStructureId"});
gspc.belongsTo(policy, { as: "policy", foreignKey: "policyId"});
policy.hasMany(gspc, { as: "gspc", foreignKey: "policyId"});
policyDeteil.belongsTo(policy, { as: "policy", foreignKey: "policyId"});
policy.hasMany(policyDeteil, { as: "policyDeteil", foreignKey: "policyId"});
policy.belongsTo(policyType, { as: "policytype", foreignKey: "policytypeId"});
policyType.hasMany(policy, { as: "policie", foreignKey: "policytypeId"});
employee.belongsTo(position, { as: "position", foreignKey: "positionId"});
position.hasMany(employee, { as: "employee", foreignKey: "positionId"});
employee.belongsTo(positionLevel, { as: "positionLevel", foreignKey: "positionLevelId"});
positionLevel.hasMany(employee, { as: "employee", foreignKey: "positionLevelId"});
flowStep.belongsTo(request, { as: "request", foreignKey: "requestId"});
request.hasMany(flowStep, { as: "flowStep", foreignKey: "requestId"});
requestActionLog.belongsTo(request, { as: "request", foreignKey: "requestId"});
request.hasMany(requestActionLog, { as: "requestActionLog", foreignKey: "requestId"});
request.belongsTo(requestType, { as: "requestType", foreignKey: "requestTypeId"});
requestType.hasMany(request, { as: "request", foreignKey: "requestTypeId"});
user.belongsTo(role, { as: "role", foreignKey: "roleId"});
role.hasMany(user, { as: "user", foreignKey: "roleId"});
request.belongsTo(status, { as: "status", foreignKey: "statusId"});
status.hasMany(request, { as: "request", foreignKey: "statusId"});
actionLog.belongsTo(user, { as: "actionUser", foreignKey: "actionUserId"});
user.hasMany(actionLog, { as: "actionLog", foreignKey: "actionUserId"});
equiepment.belongsTo(user, { as: "owner", foreignKey: "ownerId"});
user.hasMany(equiepment, { as: "equiepment", foreignKey: "ownerId"});
file.belongsTo(user, { as: "createUser", foreignKey: "createUserId"});
user.hasMany(file, { as: "file", foreignKey: "createUserId"});
flowGroupMember.belongsTo(user, { as: "user", foreignKey: "userId"});
user.hasMany(flowGroupMember, { as: "flowGroupMember", foreignKey: "userId"});
flowStep.belongsTo(user, { as: "user", foreignKey: "userId"});
user.hasMany(flowStep, { as: "flowStep", foreignKey: "userId"});
gspc.belongsTo(user, { as: "isSupporter", foreignKey: "isSupporterId"});
user.hasMany(gspc, { as: "gspc", foreignKey: "isSupporterId"});
holiday.belongsTo(user, { as: "crateUser", foreignKey: "crateUserId"});
user.hasMany(holiday, { as: "holiday", foreignKey: "crateUserId"});
holiday.belongsTo(user, { as: "updateUser", foreignKey: "updateUserId"});
user.hasMany(holiday, { as: "updateUserHoliday", foreignKey: "updateUserId"});
masterFlowStep.belongsTo(user, { as: "user", foreignKey: "userId"});
user.hasMany(masterFlowStep, { as: "masterFlowStep", foreignKey: "userId"});
request.belongsTo(user, { as: "updateUser", foreignKey: "updateUserId"});
user.hasMany(request, { as: "request", foreignKey: "updateUserId"});
request.belongsTo(user, { as: "createUser", foreignKey: "createUserId"});
user.hasMany(request, { as: "createUserRequest", foreignKey: "createUserId"});
user.belongsTo(user, { as: "createUser", foreignKey: "createUserId"});
user.hasMany(user, { as: "user", foreignKey: "createUserId"});
user.belongsTo(user, { as: "updateUser", foreignKey: "updateUserId"});
user.hasMany(user, { as: "updateUserUser", foreignKey: "updateUserId"});
stateTransition.belongsTo(stateType, { as: "stateType", foreignKey: "stateTypeId" });
stateType.hasMany(stateTransition, { as: "stateTransition", foreignKey: "stateTypeId" });
stateTransition.belongsTo(status, { as: "current", foreignKey: "currentId" });
status.hasMany(stateTransition, { as: "stateTransition", foreignKey: "currentId" });
stateTransition.belongsTo(status, { as: "next", foreignKey: "nextId" });
status.hasMany(stateTransition, { as: "nextStateTransition", foreignKey: "nextId" });